---
title: "comp5048"
author: "Yujun Liu"
date: "10/12/2019"
output: 
  html_document: 
    fig_height: 10
    fig_width: 15
---

```{r EDA}

library(ggplot2)
library(ggmap)
library(maps)
library(FSelector)   #For information.gain()
library(gridExtra)   #For grid.arrange()
library(ggthemes)


happy15 <- read.csv("C:/Users/Yujun/Desktop/COMP5048/hw2/2015.csv", header = T, sep = ",")
happy16 <- read.csv("C:/Users/Yujun/Desktop/COMP5048/hw2/2016.csv", header = T, sep = ",")
happy17 <- read.csv("C:/Users/Yujun/Desktop/COMP5048/hw2/2017.csv", header = T, sep = ",")

#Add year feature
happy15$year=2015
happy16$year=2016
happy17$year=2017

#Eliminate irrelevant features
happy15$Standard.Error=NULL
happy16$Lower.Confidence.Interval=NULL
happy16$Upper.Confidence.Interval=NULL
happy17$Upper.Confidence.Interval=NULL
happy17$Whisker.high=NULL
happy17$Whisker.low=NULL

region15=happy15$Region 
regionLevels=levels(happy15$Region)
happy15$Region=NULL     

region16=happy16$Region 
happy16$Region=NULL

happy <- rbind(happy15,happy16,happy17) 
#happy
```


``` {r EDA2}

colnames(happy) = c("country", "Happiness.rank", "Happiness.score", "GDP", "Family", "Health", "Freedom", "Government.Corruption", "Generosity", "Residual", "Year")
happy=happy[,c(11,1:3,10,4:9)]
happy$region=rep(999,470)
happy$region[1:315]=c(region15,region16) 
for (i in 316:470) 
{country=happy$country[i]; j=which(happy$country==country)[1]; happy$region[i]=happy$region[j]}


happy$country[c(348,386)] = c("Taiwan","Hong Kong") #Because country name is differnet(2015,2017)
as.numeric(region15[c(38,72)])
happy$region[c(348,386)]=3

happy$region=as.factor(happy$region)   
levels(happy$region) = regionLevels  #Convert the levels from numbers back to their original names ("Western Europe", etc.) 

happy$region = factor(happy$region) 
#happy$country[91]
#happy$country[255]

happy$country[91]="Somaliland Region"
```


``` {r map}
map = map_data("world")
#str(map)
colnames(map)[5]="country"
map$country = as.factor(map$country)
map$subregion=NULL
#which(!(levels(happy$country)%in%levels(map$country)))
levels(happy$country)[c(32,33,57,105,109,127,143,150,151,163,165,166)]
levels(happy$country)[32]="Democratic Republic of the Congo"
levels(happy$country)[109]="Palestine"
levels(happy$country)[150]="UK"
levels(happy$country)[151]="USA"
levels(happy$country)[166]="Taiwan"



happy = happy[-c(120,283,441,66,220,376,41,201,353,72,233,386,91,255),]   #Remove the undesired rows
happy$country = factor(happy$country) #Remove empty factors 

#happy
happy = happy[,c(1:2,12,3:11)] 
merge = merge(map,happy,by="country", all.x=TRUE) 
merge = merge[order(merge$order),] 
merge$Happiness.score[merge$country=="Trinidad"] = 6.168
merge$Happiness.score[merge$country=="Tobago"] = 6.168
#sum(is.na(merge$country))
#merge
#happy
```

Univariate Analysis: The Six Characteristics
``` {r}
whr2015=subset(happy,Year==2015)
whr2016=subset(happy,Year==2016)
#dim(whr2016)
whr2017=subset(happy,Year==2017)
happyt=rbind(whr2015,whr2016,whr2017)
#happyt
table(happyt$region)
#write.csv(happyt, "happytotal.csv")
```


``` {r}
par(mfrow=c(3,2))

hist(happyt$GDP, xlab=NULL, main="GDP Per Capita (2015-2017)", col="brown")
hist(happyt$Health, xlab=NULL, main="Health (2015-2017)", col="brown")
hist(happyt$Family, xlab=NULL, main="Family (2015-2017)", col="brown")
hist(happyt$Freedom, xlab=NULL, main="Freedom (2015-2017)", col="brown")
hist(happyt$Government.Corruption, xlab=NULL, main="Trust In Government (2015-2017)", col="brown")
hist(happyt$Generosity, xlab=NULL,main="Generosity (2015-2017)", col="brown")
```


``` {r feature}
ggplot(happyt, aes(y=Happiness.score, x=region, fill=region)) + geom_boxplot() + labs(title="Happiness Boxplots By Region (2015-2016)", y="Happiness Score") + theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) + scale_fill_discrete(name="Region") 
```


